/* INFO */
export const RECIEVE_INFO = 'RECIEVE_INFO'

/* Vote */
export const REMOVE_VOTE_FROM_BUSY = 'REMOVE_VOTE_FROM_BUSY'
export const ADD_VOTE_TO_BUSY = 'ADD_VOTE_TO_BUSY'
export const ADD_VOTE = 'ADD_VOTE'
export const RECIEVE_VOTES = 'RECIEVE_VOTES'

/* Forum */
export const SET_CURRENT_TOPIC = 'SET_CURRENT_TOPIC'
export const RECIEVE_TOPICS = 'RECIEVE_TOPICS'

/* Dialog element */
export const SET_RESULT_CONFIRM_DIALOG = 'SET_RESULT_CONFIRM_DIALOG'
export const SHOW_CONGRATULATION_DIALOG = 'SHOW_CONGRATULATION_DIALOG'
export const CLEAR_MESSAGE_DIALOG = 'CLEAR_MESSAGE_DIALOG'
export const SET_MESSAGE_DIALOG = 'SET_MESSAGE_DIALOG'
// export const SET_CONFIRM_DIALOG_RESULT = 'SET_CONFIRM_DIALOG_RESULT'
// export const RESET_CONFIRM_DIALOG_RESULT = 'RESET_CONFIRM_DIALOG_RESULT'

/* Busy element */
export const SET_LOADING = 'SET_LOADING'

/* User */
export const GET_ALL_USERS = 'GET_ALL_USERS'

/* Auth */
export const SET_ADMIN_ROLE = 'SET_ADMIN_ROLE'
export const RESET_PAGE_OF_USERS = 'RESET_PAGE_OF_USERS'
export const INCREASE_PAGE_OF_USERS = 'INCREASE_PAGE_OF_USERS'
export const RECIEVE_NEXT_PART_OF_USERS = 'RECIEVE_NEXT_PART_OF_USERS'
export const RECIEVE_ALL_USERS = 'RECIEVE_ALL_USERS'
export const RECIEVE_USER_SETTINGS = 'RECIEVE_USER_SETTINGS'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_ERRORS = 'SET_ERRORS'
export const SET_USER = 'SET_USER'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const SET_TOKEN = 'SET_TOKEN'

// /* auth */
// export const GET_USER = 'GET_USER';
// export const LOGIN = 'LOGIN';
// export const LOGOUT = 'LOGOUT';
